applicationName: school-management-system

authServer:
  serviceName: auth-server
  servicePort: 5698
  imageSource: dockerallang/school-management-auth-server
  imageTag: latest
  database: school_management_auth
  
  
dbServer:   
  host: mysql-service 
  port: 3306

keyStore:
  password: cnd80751xh

kafkaService:
  serviceName: kafka-service
  port: 9092

userService: 
  serviceName: user-management-service
  imageSource: dockerallang/school-management-user-service
  imageTag: latest
  port: 5700  
  database: school_management_user_service

notificationService:
  serviceName: auth-server
  servicePort: 5699
  imageSource: dockerallang/school-management-notification
  imageTag: latest
  database: school_management_notification
  
 
  

  

